const dummyUsers = [
    {
        pan: 'ABCDE1234F',
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: 9876543210,
        address: '123 Elm Street',
        pincode: 110001,
        state: 'Delhi',
        city: 'Delhi',
        role: 'user',
    },
    {
        pan: 'FGHIJ5678K',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: 8765432109,
        address: '456 Oak Avenue',
        pincode: 110002,
        state: 'Delhi',
        city: 'Delhi',
        role: 'admin',
    },
    {
        pan: 'KLMNO9876P',
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        phone: 7654321098,
        address: '789 Pine Road',
        pincode: 110003,
        state: 'Delhi',
        city: 'Delhi',
        role: 'user',
    },
    {
        pan: 'QRSTU5432V',
        name: 'Bob Brown',
        email: 'bob.brown@example.com',
        phone: 6543210987,
        address: '321 Maple Street',
        pincode: 110004,
        state: 'Delhi',
        city: 'Delhi',
        role: 'user',
    },
];